services:
  - type: web
    name: tera-bot
    runtime: docker
    plan: free
    repo: https://github.com/CPUZ-0001/TERA-BOT.git
    dockerfilePath: Dockerfile
    dockerCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_API
        sync: false
      - key: TELEGRAM_HASH
        sync: false
      - key: FSUB_ID
        sync: false
      - key: DUMP_CHAT_ID
        sync: false
